# Generated by Django 3.1.7 on 2021-03-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='content',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
