# Generated by Django 3.1.7 on 2021-03-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20210308_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='most_recent_refresh_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
